### PR TITLE
Update wireguard-server.sh

### LINKED ISSUE #131: Existing ad-blocking DNS configuration
I suggest an option to configure the user's own DNS server address, e.g. I have dnsmasq running on my router and use this for all DNS queries on my internal LAN (ip 192.168.1.1).

Thanks for the script, I found it made it very easy to configure wireguard.

### PR DESCRIPTION
**Pull request by Just-Insane**
Adds support for custom DNS servers. Closes #131

### CODE REVIEW

**Comment by Prajwal-Koirala** [comment]
The problem with custom input DNS is that we need 4x of them.

1. Primary IPv4
2. Backup IPv4
3. Primary IPv6
4. Backup IPv6

**Comment by Just-Insane** [comment]
Is there anything specific that requires 4 DNS servers? I don't see anything in the server config that seems related.

Unless it's hardcoded in the wireguard config, I doubt it is necessary to have 4.

**Comment by Prajwal-Koirala** [comment]
Since the script supports IPv6 we need at least 2x.

1. Primary IPv4
2. Primary IPv6

**Comment by Prajwal-Koirala** [comment]
Formatting: ```0.0.0.0,0000:0000:0000:0000:0000:0000:0000:0000```

**Comment by Prajwal-Koirala** [comment]
Dude this is good code, please don't close it, I'll work on it and merge it soon.

**Comment by Prajwal-Koirala** [comment]
Thank you for this

This was added on
https://github.com/complexorganizations/wireguard-manager/commit/910d57d6028cf60f40b9585011fe5be7ae24eabe

Please make a pull on read me if you want some credits.

**Pull request closed without merging**
